import{uid,today,future,project,openDB,allEvents,record}from './data.js';
import{configured,owner,connected,hasLegacy,pair,sync,recoverLegacy}from './cloud.js';
import{home,syllabus,planner}from './ui.js';
import{leaves,progress,topicPath}from './study.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={hoje:'Hoje',edital:'Meu edital',plano:'Planejamento',dados:'Desempenho'};
const paths=['M3 10 12 3 21 10V21H3Z M9 21V13H15V21','M5 3H19V21H5Z M8 8H16 M8 12H16 M8 16H13','M4 5H20V21H4Z M8 2V8 M16 2V8 M4 10H20','M4 20H21 M7 17V12 M12 17V7 M17 17V3'];
$('#nav').innerHTML=Object.entries(names).map(([k,v],i)=>`<a href="#${k}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[i]}"/></svg>${v}</a>`).join('');
let state=[],events=[],active=localStorage.getItem('estudo-active')||'',tab='hoje',filter='',filterState='all',day=new Date().getDay(),syncError='';
const entities=k=>state.filter(x=>x.kind===k),exam=()=>entities('exam').find(x=>x.id===active),items=k=>entities(k).filter(x=>x.exam===active),subject=id=>entities('subject').find(x=>x.id===id),topic=id=>entities('topic').find(x=>x.id===id),fmt=d=>d?d.split('-').reverse().join('/'):'Sem data',pct=(a,b)=>b?Math.round(a/b*100):0;
const button=(text,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
const field=(name,label,type='text',value='',attrs='')=>`<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}>`;
const select=(name,label,opts)=>`<label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${opts}</select>`;
const options=rows=>rows.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');

let openKeys;try{openKeys=new Set(JSON.parse(localStorage.getItem('estudo-open')||'[]'))}catch{openKeys=new Set()}
function persistOpen(){localStorage.setItem('estudo-open',JSON.stringify([...openKeys]))}
function context(){return {items,exam,topic,subject,esc,button,filter,filterState,day,today,future,reviews,timerHTML,planRows,connected,hasLegacy,isOpen:key=>openKeys.has(key)}}
document.addEventListener('toggle',e=>{const el=e.target;if(!el.isConnected||!el.dataset.openKey)return;el.open?openKeys.add(el.dataset.openKey):openKeys.delete(el.dataset.openKey);persistOpen()},true);
function applyTheme(value=localStorage.getItem('estudo-theme')||'system'){document.body.classList.toggle('dark',value==='dark'||(value==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));localStorage.setItem('estudo-theme',value)}
function notice(message){$('#notice').textContent=message}
function modal(title,html){$('#dialog-content').innerHTML=`<h2 id="modal-title">${title}</h2>${html}`;$('#dialog').showModal()}
function form(title,html,fn){modal(title,`<form id="edit-form">${html}<div class="actions"><button class="primary">Salvar</button></div><p class="help" id="form-error" role="alert"></p></form>`);$('#edit-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter||e.target.querySelector('button.primary');b.disabled=true;try{await fn(new FormData(e.target));$('#dialog').close();await refresh();void synchronize()}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}}}
async function save(kind,id,payload){await record(owner(),kind,id||uid(),payload)}
function needExam(){if(exam())return true;notice('Aguardando configuração do edital.');return false}
function stats(){const ss=items('session'),p=progress(items('topic'));return{minutes:ss.reduce((a,x)=>a+x.minutes,0),q:ss.reduce((a,x)=>a+x.questions,0),right:ss.reduce((a,x)=>a+x.right,0),done:p.done,total:p.total}}
function stat(label,value,detail){return `<div class="stat"><small>${label}</small><strong>${value}</strong><small>${detail}</small></div>`}
function planRows(rows){return rows.length?rows.map(p=>`<div class="row"><div><small>${esc(p.time)} · ${p.minutes} MIN</small><h3>${esc(topic(p.topic)?.name||'Assunto')}</h3></div>${button('Iniciar','start',p.topic)}</div>`).join(''):'<p class="empty">Nenhum bloco previsto para hoje.</p>'}
function reviews(){return items('review').filter(r=>!r.done&&r.date<=today()&&topic(r.topic)).sort((a,b)=>a.date.localeCompare(b.date))}
function reviewRows(){return reviews().map(r=>`<div class="row"><div><h3>${esc(topic(r.topic)?.name)}</h3><p class="muted">${r.date<today()?'Atrasada · ':''}${fmt(r.date)}</p></div><div class="actions">${button('Registrar','review',r.id)}${button('Reagendar','reschedule',r.id)}</div></div>`).join('')||'<p class="empty">Nenhuma revisão pendente para hoje.</p>'}
function renderToday(){return home(context())}
function renderEdital(){return syllabus(context())}
function renderPlan(){return planner(context())}
function renderData(){const s=stats();return `<div class="toolbar">${button('Registrar sessão','session','','primary')}${button('Salvar simulado','mock')}</div><div class="stats">${stat('Tempo total',(s.minutes/60).toFixed(1)+' h','Sessões registradas')}${stat('Questões',s.q,'Total resolvido')}${stat('Acertos',s.right,'Total correto')}${stat('Aproveitamento',s.q?pct(s.right,s.q)+'%':'—','Acertos / questões')}</div><section class="card"><h2>Por disciplina</h2>${items('subject').map(sub=>{const logs=items('session').filter(x=>x.subject===sub.id),q=logs.reduce((a,x)=>a+x.questions,0),r=logs.reduce((a,x)=>a+x.right,0);return `<div class="row"><div style="width:100%"><h3>${esc(sub.name)}</h3><small>${q} questões · ${q?pct(r,q)+'% de acertos':'sem amostra'}</small><div class="bar"><span style="width:${pct(r,q)}%"></span></div></div></div>`}).join('')||'<p class="empty">Sem dados para comparar.</p>'}</section><div class="grid"><section class="card"><h2>Histórico de sessões</h2>${items('session').sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><h3>${esc(x.name)}</h3><p class="muted">${fmt(x.date)} · ${x.minutes} min · ${x.right}/${x.questions} acertos</p></div>${button('Excluir','delete',x.id)}</div>`).join('')||'<p class="empty">Suas sessões aparecerão aqui.</p>'}</section><section class="card"><h2>Simulados</h2>${items('mock').sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><h3>${esc(x.name)}</h3><p>${x.score.toFixed(1)} / ${x.max.toFixed(1)} pontos · ${fmt(x.date)}</p><p class="muted">${x.parts.map(p=>esc(p.name)+': '+p.right+'/'+p.total).join(' · ')}</p></div>${button('Excluir','delete',x.id)}</div>`).join('')||'<p class="empty">Registre um simulado para acompanhar sua evolução.</p>'}</section></div>`}
async function refresh(){events=(await allEvents()).filter(e=>e.owner===owner());state=project(events);if(!exam()){active=entities('exam')[0]?.id||'';localStorage.setItem('estudo-active',active)}render()}
function render(){tab=location.hash.slice(1);if(!names[tab])tab='hoje';$('#title').textContent=names[tab];$('#eyebrow').textContent='BACEN · SUPORTE TÉCNICO ADMINISTRATIVO';document.querySelectorAll('nav a').forEach(a=>(a.classList.toggle('active',a.hash==='#'+tab),a.hash==='#'+tab?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')));$('#content').innerHTML=({hoje:renderToday,edital:renderEdital,plano:renderPlan,dados:renderData}[tab]||renderToday)();const pending=events.filter(x=>!x.synced).length;$('#sync').textContent=!connected()?'Neste aparelho':!navigator.onLine?'Sem conexão':syncError?'Falha ao sincronizar':pending?pending+' alterações pendentes':'Sincronizado';}
async function synchronize(){if(!connected())return;try{await sync();syncError='';await refresh()}catch(e){syncError=e.message;render();notice('Registros locais preservados. Supabase: '+e.message)}}
function getTimer(){try{return JSON.parse(localStorage.getItem('estudo-timer-'+owner())||'null')}catch{return null}}
function storeTimer(t){localStorage.setItem('estudo-timer-'+owner(),JSON.stringify(t))}
function elapsed(t){return t.elapsed+(t.running?Date.now()-t.started:0)}
function clock(ms){const sec=Math.floor(ms/1000);return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function timerHTML(){const t=getTimer();return t?`<section class="card"><small>SESSÃO EM ANDAMENTO</small><h3>${esc(t.name)}</h3><div class="timer" id="clock">${clock(elapsed(t))}</div><div class="actions">${button(t.running?'Pausar':'Continuar','pause')}${button('Finalizar e registrar','finish','','primary')}${button('Descartar','discard')}</div></section>`:''}
function lockTopic(id){$('#f-topic').disabled=true;const hidden=document.createElement('input');hidden.type='hidden';hidden.name='topic';hidden.value=id;$('#edit-form').append(hidden)}
function sessionForm(topicId,reviewId='',timer=null){if(!needExam())return;const ts=leaves(items('topic')).map(t=>({...t,name:topicPath(items('topic'),t.id)}));if(!ts.length)throw Error('Aguardando tópicos do edital.');form('Registrar estudo',select('topic','Assunto',options(ts))+field('date','Data','date',today(),'required')+`<div class="fields"><div>${field('minutes','Minutos estudados','number',timer?Math.max(1,Math.round(elapsed(timer)/60000)):30,'min="1" max="1440" required')}</div><div>${select('type','Modalidade','<option>Teoria</option><option>Questões</option><option>Revisão</option>')}</div><div>${field('questions','Questões respondidas','number',0,'min="0" max="10000" required')}</div><div>${field('right','Acertos','number',0,'min="0" max="10000" required')}</div></div><label class="check"><input name="complete" type="checkbox">Marcar assunto estudado e programar revisões</label>`,async f=>{const t=topic(f.get('topic')),q=Number(f.get('questions')),r=Number(f.get('right'));if(r>q)throw Error('Acertos não podem superar questões respondidas.');if(f.get('date')>today())throw Error('Uma sessão realizada não pode ter data futura.');await save('session',null,{exam:active,topic:t.id,subject:t.subject,name:t.name,date:f.get('date'),minutes:Number(f.get('minutes')),questions:q,right:r,type:f.get('type')});if(reviewId)await save('review',reviewId,{done:true});if(f.has('complete'))await complete(t,f.get('date'));if(timer)storeTimer(null)});$('#f-topic').value=topicId||ts[0].id;if(reviewId)$('#f-type').value='Revisão';if(timer||reviewId)$('#f-topic').setAttribute('aria-readonly','true')}
async function complete(t,date=today()){await save('topic',t.id,{status:'done'});if(!items('review').some(r=>r.topic===t.id)){for(const n of (exam()?.intervals||'7,15,30').split(',').map(Number))await save('review',null,{exam:active,topic:t.id,date:future(date,n),done:false})}}
const actions={
 async toggle(id){const t=topic(id);if(t.status==='done')await save('topic',id,{status:'pending'});else await complete(t);await refresh();void synchronize()},
 start(id){if(getTimer())throw Error('Finalize ou descarte a sessão atual na tela Hoje.');const t=topic(id);if(!t)throw Error('Assunto não encontrado.');storeTimer({topic:id,exam:active,name:t.name,started:Date.now(),elapsed:0,running:true});location.hash='hoje';render()},
 pause(){const t=getTimer();if(!t)return;storeTimer({...t,elapsed:elapsed(t),started:Date.now(),running:!t.running});render()},
 finish(){const t=getTimer();if(!t)return;storeTimer({...t,elapsed:elapsed(t),running:false});active=t.exam;sessionForm(t.topic,'',getTimer());lockTopic(t.topic);render()},
 discard(){if(confirm('Descartar o cronômetro sem registrar esta sessão?')){storeTimer(null);render()}},
 session(id){sessionForm(id)},review(id){const r=items('review').find(x=>x.id===id);sessionForm(r.topic,id);lockTopic(r.topic)},
 reschedule(id){const r=items('review').find(x=>x.id===id);form('Reagendar revisão',field('date','Nova data','date',r.date,'required'),async f=>save('review',id,{date:f.get('date')}))},
 day(id){day=Number(id);render()},
 async delete(id){const x=state.find(x=>x.id===id);if(confirm('Excluir este registro?')){await save(x.kind,id,{deleted:true});await refresh();void synchronize()}},
 mock(){if(!needExam())return;const subs=items('subject');if(!subs.length)throw Error('Cadastre disciplinas e seus pesos primeiro.');form('Registrar simulado',field('name','Identificação','text','','required maxlength="160"')+field('date','Data','date',today(),'required')+subs.map(s=>`<h3 style="margin-top:20px">${esc(s.name)} · peso ${s.weight}</h3><div class="fields"><div>${field('q-'+s.id,'Total de questões','number',0,'min="0" max="10000" required')}</div><div>${field('r-'+s.id,'Acertos','number',0,'min="0" max="10000" required')}</div></div>`).join('')+'<p class="help">Cálculo por acertos × peso.</p>',async f=>{const parts=subs.map(s=>({name:s.name,total:Number(f.get('q-'+s.id)),right:Number(f.get('r-'+s.id)),weight:s.weight}));if(parts.some(p=>p.right>p.total))throw Error('Confira os acertos por disciplina.');const max=parts.reduce((a,p)=>a+p.total*p.weight,0);if(!max)throw Error('Informe ao menos uma questão.');await save('mock',null,{exam:active,name:f.get('name'),date:f.get('date'),parts,max,score:parts.reduce((a,p)=>a+p.right*p.weight,0)})})},
 theme(){applyTheme(document.body.classList.contains('dark')?'light':'dark')},
 'go-edital'(){location.hash='edital'}, 'go-plan'(){location.hash='plano'},
 'open-subject'(id){openKeys.add('subject:'+id);persistOpen();location.hash='edital';render()},
 expand(){for(const sub of items('subject'))openKeys.add('subject:'+sub.id);for(const t of items('topic'))if(items('topic').some(x=>x.parent===t.id))openKeys.add('topic:'+t.id);persistOpen();render()},
 collapse(){openKeys.clear();persistOpen();render()},
 async sync(){await synchronize()}
};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{await actions[b.dataset.action]?.(b.dataset.id)}catch(err){notice(err.message)}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;filter=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.id==='filter'){filterState=e.target.value;render()}});
$('#theme').onclick=actions.theme;$('#sync').onclick=actions.sync;window.addEventListener('hashchange',render);window.addEventListener('online',()=>void synchronize());window.addEventListener('offline',render);window.addEventListener('focus',()=>void refresh().then(synchronize));
setInterval(()=>{const t=getTimer();if(t&&$('#clock'))$('#clock').textContent=clock(elapsed(t))},1000);setInterval(()=>{if(navigator.onLine&&!$('#dialog').open)void synchronize()},30000);
applyTheme();matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(localStorage.getItem('estudo-theme')==='system')applyTheme()});
try{await openDB();await refresh();void synchronize()}catch(e){notice('Não foi possível abrir o armazenamento local. '+e.message)}
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>notice('Não foi possível ativar o modo offline.'));
