import{uid,today,future,project,openDB,allEvents,record}from './data.js';
import{configured,owner,email,login,logout,sync,adoptLocal}from './cloud.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={hoje:'Hoje',edital:'Edital',plano:'Planejamento',dados:'Desempenho',config:'Configurações'};
const paths=['M3 10 12 3 21 10V21H3Z M9 21V13H15V21','M5 3H19V21H5Z M8 8H16 M8 12H16 M8 16H13','M4 5H20V21H4Z M8 2V8 M16 2V8 M4 10H20','M4 20H21 M7 17V12 M12 17V7 M17 17V3','M4 7H20 M4 17H20 M9 3V11 M15 13V21'];
$('#nav').innerHTML=Object.entries(names).map(([k,v],i)=>`<a href="#${k}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[i]}"/></svg>${v}</a>`).join('');
let state=[],events=[],active=localStorage.getItem('estudo-active')||'',tab='hoje',filter='',filterState='all',day=new Date().getDay(),syncError='';
const entities=k=>state.filter(x=>x.kind===k),exam=()=>entities('exam').find(x=>x.id===active),items=k=>entities(k).filter(x=>x.exam===active),subject=id=>entities('subject').find(x=>x.id===id),topic=id=>entities('topic').find(x=>x.id===id),fmt=d=>d?d.split('-').reverse().join('/'):'Sem data',pct=(a,b)=>b?Math.round(a/b*100):0;
const button=(text,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
const field=(name,label,type='text',value='',attrs='')=>`<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}>`;
const select=(name,label,opts)=>`<label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${opts}</select>`;
const options=rows=>rows.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
function notice(message){$('#notice').textContent=message}
function modal(title,html){$('#dialog-content').innerHTML=`<h2>${title}</h2>${html}`;$('#dialog').showModal()}
function form(title,html,fn){modal(title,`<form id="edit-form">${html}<div class="actions"><button class="primary">Salvar</button></div><p class="help" id="form-error" role="alert"></p></form>`);$('#edit-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await fn(new FormData(e.target));$('#dialog').close();await refresh();void synchronize()}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}}}
async function save(kind,id,payload){await record(owner(),kind,id||uid(),payload)}
function needExam(){if(exam())return true;notice('Cadastre um concurso em Configurações para começar.');location.hash='config';return false}
function stats(){const ss=items('session'),ts=items('topic');return{minutes:ss.reduce((a,x)=>a+x.minutes,0),q:ss.reduce((a,x)=>a+x.questions,0),right:ss.reduce((a,x)=>a+x.right,0),done:ts.filter(x=>x.status==='done').length,total:ts.length}}
function stat(label,value,detail){return `<div class="stat"><small>${label}</small><strong>${value}</strong><small>${detail}</small></div>`}
function planRows(rows){return rows.length?rows.map(p=>`<div class="row"><div><small>${esc(p.time)} · ${p.minutes} MIN</small><h3>${esc(topic(p.topic)?.name||'Assunto removido')}</h3></div>${button('Iniciar','start',p.topic)}${button('Excluir','delete',p.id)}</div>`).join(''):'<p class="empty">Nenhum bloco previsto. Organize sua semana em Planejamento.</p>'}
function reviews(){return items('review').filter(r=>!r.done&&r.date<=today()&&topic(r.topic))}
function reviewRows(){return reviews().map(r=>`<div class="row"><div><h3>${esc(topic(r.topic)?.name)}</h3><p class="muted">${r.date<today()?'Atrasada · ':''}${fmt(r.date)}</p></div><div class="actions">${button('Registrar','review',r.id)}${button('Reagendar','reschedule',r.id)}</div></div>`).join('')||'<p class="empty">Nenhuma revisão pendente para hoje.</p>'}
function renderToday(){const s=stats(),plans=items('plan').filter(p=>p.day===new Date().getDay()).sort((a,b)=>a.time.localeCompare(b.time)),t=topic(plans[0]?.topic)||items('topic').find(t=>t.status!=='done');const start=new Date();start.setDate(start.getDate()-((start.getDay()+6)%7));const week=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}-${String(start.getDate()).padStart(2,'0')}`;const minutes=items('session').filter(x=>x.date>=week).reduce((a,x)=>a+x.minutes,0);return `<section class="hero"><small>${esc(exam()?.name||'UM NOVO CICLO DE ESTUDOS')}</small><h2>${t?esc(t.name):'Seu próximo objetivo começa aqui.'}</h2><p class="muted">${t?esc(subject(t.subject)?.name||'')+' · Retome o plano no seu ritmo.':'Cadastre o concurso e seus assuntos. O plano acompanha você.'}</p>${t?button('Iniciar estudo','start',t.id):button('Configurar concurso','exam')}</section>${timerHTML()}<div class="stats">${stat('Estudo nesta semana',`${(minutes/60).toFixed(1)} h`,'Tempo efetivamente registrado')}${stat('Cobertura do edital',pct(s.done,s.total)+'%',s.done+' de '+s.total+' assuntos')}${stat('Aproveitamento',s.q?pct(s.right,s.q)+'%':'—',s.q+' questões registradas')}${stat('Revisões pendentes',reviews().length,'Vencidas ou previstas para hoje')}</div><div class="grid"><section class="card"><h2>Seu plano de hoje</h2>${planRows(plans)}</section><section class="card"><h2>Revisões</h2>${reviewRows()}</section></div>`}
function renderEdital(){const topics=items('topic').filter(t=>(!filter||t.name.toLocaleLowerCase().includes(filter.toLocaleLowerCase()))&&(filterState==='all'||(filterState==='pending'?t.status!=='done':t.status==='done')));return `<div class="toolbar"><input id="search" aria-label="Buscar assunto" placeholder="Buscar no edital" value="${esc(filter)}"><select id="filter" aria-label="Filtrar progresso"><option value="all">Todos os assuntos</option><option value="pending" ${filterState==='pending'?'selected':''}>Não concluídos</option><option value="done" ${filterState==='done'?'selected':''}>Estudados</option></select>${button('Nova disciplina','subject')}${button('Adicionar assuntos','topics','','primary')}</div>${items('subject').map(s=>{const ts=topics.filter(t=>t.subject===s.id);return `<details open><summary>${esc(s.name)} <span class="pill">Peso ${s.weight}</span></summary>${ts.map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p class="muted">${t.status==='done'?'Estudado':'Não concluído'}</p></div><div class="topic-actions">${button('Estudar','start',t.id)}${button('Registrar sessão','session',t.id)}${button(t.status==='done'?'Reabrir':'Marcar estudado','toggle',t.id)}${button('Detalhes','detail',t.id)}</div></div>`).join('')||'<p class="empty">Nenhum assunto neste filtro.</p>'}</details>`}).join('')||'<section class="card empty">Adicione as disciplinas e os assuntos do novo edital. Não carregamos dados do concurso anterior.</section>'}`}
function renderPlan(){const days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];return `<div class="toolbar">${button('Novo bloco semanal','plan','','primary')}${button('Registrar sessão','session')}</div><section class="card"><h2>Agenda semanal</h2><div class="day-tabs">${days.map((x,i)=>`<button data-action="day" data-id="${i}" aria-pressed="${day===i}">${x}</button>`).join('')}</div>${planRows(items('plan').filter(p=>p.day===day).sort((a,b)=>a.time.localeCompare(b.time)))}</section><section class="card"><h2>Fila de revisões</h2>${reviewRows()}</section>`}
function renderData(){const s=stats();return `<div class="toolbar">${button('Registrar sessão','session','','primary')}${button('Salvar simulado','mock')}</div><div class="stats">${stat('Tempo total',(s.minutes/60).toFixed(1)+' h','Sessões registradas')}${stat('Questões',s.q,'Total resolvido')}${stat('Acertos',s.right,'Total correto')}${stat('Aproveitamento',s.q?pct(s.right,s.q)+'%':'—','Acertos / questões')}</div><section class="card"><h2>Por disciplina</h2>${items('subject').map(sub=>{const logs=items('session').filter(x=>x.subject===sub.id),q=logs.reduce((a,x)=>a+x.questions,0),r=logs.reduce((a,x)=>a+x.right,0);return `<div class="row"><div style="width:100%"><h3>${esc(sub.name)}</h3><small>${q} questões · ${q?pct(r,q)+'% de acertos':'sem amostra'}</small><div class="bar"><span style="width:${pct(r,q)}%"></span></div></div></div>`}).join('')||'<p class="empty">Sem dados para comparar.</p>'}</section><div class="grid"><section class="card"><h2>Histórico de sessões</h2>${items('session').sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><h3>${esc(x.name)}</h3><p class="muted">${fmt(x.date)} · ${x.minutes} min · ${x.right}/${x.questions} acertos</p></div>${button('Excluir','delete',x.id)}</div>`).join('')||'<p class="empty">Suas sessões aparecerão aqui.</p>'}</section><section class="card"><h2>Simulados</h2>${items('mock').sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><h3>${esc(x.name)}</h3><p>${x.score.toFixed(1)} / ${x.max.toFixed(1)} pontos · ${fmt(x.date)}</p><p class="muted">${x.parts.map(p=>esc(p.name)+': '+p.right+'/'+p.total).join(' · ')}</p></div>${button('Excluir','delete',x.id)}</div>`).join('')||'<p class="empty">Registre um simulado para acompanhar sua evolução.</p>'}</section></div>`}
function renderConfig(){return `<div class="grid"><section class="card"><h2>Concurso ativo</h2><label for="exam-select">Selecione um concurso</label><select id="exam-select"><option value="">Selecione</option>${entities('exam').map(x=>`<option value="${x.id}" ${x.id===active?'selected':''}>${esc(x.name)}</option>`).join('')}</select><p class="muted">${exam()?`Prova: ${fmt(exam().date)}<br>Revisões: ${esc(exam().intervals)} dias`:'Nenhum concurso cadastrado.'}</p><div class="actions">${button('Novo concurso','exam')}${exam()?button('Editar','exam',active):''}</div><p class="help">Cada concurso mantém seu próprio edital e histórico. Não é necessário apagar o anterior.</p></section><section class="card"><h2>Conta e sincronização</h2><p>${email()?esc(email()):'Você está usando o modo local.'}</p><p class="help">${configured?'A conexão está configurada. Entre para sincronizar seus aparelhos.':'Preencha a URL e a chave pública em config.js, seguindo o guia incluído no pacote.'}</p><div class="actions">${email()?button('Sincronizar agora','sync')+button('Sair da conta','logout'):button('Entrar ou criar conta','login','','primary')}</div><p class="help">Dados locais não são backup. O modo offline sincroniza enquanto a aplicação está aberta e a conexão volta.</p></section><section class="card"><h2>Aparência</h2><p class="muted">Interface sem animações decorativas ou gamificação.</p>${button('Alternar claro / escuro','theme')}</section><section class="card"><h2>Seus dados</h2><p class="help">Exporte uma cópia do histórico atual. Restaurar combina registros por identificador, sem duplicar eventos.</p><div class="actions">${button('Exportar backup','backup')}${button('Restaurar backup','restore')}</div></section></div>`}
async function refresh(){events=(await allEvents()).filter(e=>e.owner===owner());state=project(events);if(!exam()){active=entities('exam')[0]?.id||'';localStorage.setItem('estudo-active',active)}render()}
function render(){tab=location.hash.slice(1);if(!names[tab])tab='hoje';$('#title').textContent=names[tab];$('#eyebrow').textContent=exam()?.name||'SEU PLANO, EM PRÁTICA';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+tab));$('#content').innerHTML=({hoje:renderToday,edital:renderEdital,plano:renderPlan,dados:renderData,config:renderConfig}[tab])();const pending=events.filter(x=>!x.synced).length;$('#sync').textContent=owner()==='local'?'Modo local':!navigator.onLine?'Sem conexão':syncError?'Falha ao sincronizar':pending?pending+' alterações pendentes':'Sincronizado';}
async function synchronize(){if(owner()==='local')return;try{await sync();syncError='';await refresh()}catch(e){syncError=e.message;render();notice('Registros preservados neste aparelho. Nuvem: '+e.message)}}
function getTimer(){try{return JSON.parse(localStorage.getItem('estudo-timer-'+owner())||'null')}catch{return null}}
function storeTimer(t){localStorage.setItem('estudo-timer-'+owner(),JSON.stringify(t))}
function elapsed(t){return t.elapsed+(t.running?Date.now()-t.started:0)}
function clock(ms){const sec=Math.floor(ms/1000);return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function timerHTML(){const t=getTimer();return t?`<section class="card"><small>SESSÃO EM ANDAMENTO</small><h3>${esc(t.name)}</h3><div class="timer" id="clock">${clock(elapsed(t))}</div><div class="actions">${button(t.running?'Pausar':'Continuar','pause')}${button('Finalizar e registrar','finish','','primary')}${button('Descartar','discard')}</div></section>`:''}
function lockTopic(id){$('#f-topic').disabled=true;const hidden=document.createElement('input');hidden.type='hidden';hidden.name='topic';hidden.value=id;$('#edit-form').append(hidden)}
function sessionForm(topicId,reviewId='',timer=null){if(!needExam())return;const ts=items('topic');if(!ts.length)throw Error('Adicione assuntos ao edital primeiro.');form('Registrar estudo',select('topic','Assunto',options(ts))+field('date','Data','date',today(),'required')+`<div class="fields"><div>${field('minutes','Minutos estudados','number',timer?Math.max(1,Math.round(elapsed(timer)/60000)):30,'min="1" max="1440" required')}</div><div>${select('type','Modalidade','<option>Teoria</option><option>Questões</option><option>Revisão</option>')}</div><div>${field('questions','Questões respondidas','number',0,'min="0" max="10000" required')}</div><div>${field('right','Acertos','number',0,'min="0" max="10000" required')}</div></div><label class="check"><input name="complete" type="checkbox">Marcar assunto estudado e programar revisões</label>`,async f=>{const t=topic(f.get('topic')),q=Number(f.get('questions')),r=Number(f.get('right'));if(r>q)throw Error('Acertos não podem superar questões respondidas.');if(f.get('date')>today())throw Error('Uma sessão realizada não pode ter data futura.');await save('session',null,{exam:active,topic:t.id,subject:t.subject,name:t.name,date:f.get('date'),minutes:Number(f.get('minutes')),questions:q,right:r,type:f.get('type')});if(reviewId)await save('review',reviewId,{done:true});if(f.has('complete'))await complete(t,f.get('date'));if(timer)storeTimer(null)});$('#f-topic').value=topicId||ts[0].id;if(reviewId)$('#f-type').value='Revisão';if(timer||reviewId)$('#f-topic').setAttribute('aria-readonly','true')}
async function complete(t,date=today()){await save('topic',t.id,{status:'done'});if(!items('review').some(r=>r.topic===t.id)){for(const n of (exam().intervals||'7,15,30').split(',').map(Number))await save('review',null,{exam:active,topic:t.id,date:future(date,n),done:false})}}
const actions={
 exam(id){const x=entities('exam').find(e=>e.id===id);form(x?'Editar concurso':'Novo concurso',field('name','Nome do concurso e cargo','text',x?.name||'','required maxlength="180"')+field('date','Data da prova (opcional)','date',x?.date||'')+field('intervals','Intervalos de revisão, separados por vírgula','text',x?.intervals||'7,15,30','required')+'<p class="help">Alterar os intervalos afeta novas revisões, não a agenda já criada.</p>',async f=>{const intervals=f.get('intervals').split(',').map(x=>Number(x.trim()));if(intervals.length>10||intervals.some(n=>!Number.isInteger(n)||n<1||n>365))throw Error('Informe até dez intervalos inteiros entre 1 e 365 dias.');const key=id||uid();await save('exam',key,{name:f.get('name').trim(),date:f.get('date'),intervals:[...new Set(intervals)].sort((a,b)=>a-b).join(',')});active=key;localStorage.setItem('estudo-active',active)})},
 subject(){if(!needExam())return;form('Nova disciplina',field('name','Nome','text','','required maxlength="160"')+field('weight','Pontos por questão','number',1,'min="0.01" max="1000" step="0.01" required'),async f=>save('subject',null,{exam:active,name:f.get('name').trim(),weight:Number(f.get('weight'))}))},
 topics(){if(!needExam())return;if(!items('subject').length)throw Error('Crie uma disciplina primeiro.');form('Adicionar assuntos',select('subject','Disciplina',options(items('subject')))+'<label for="f-topics">Um assunto por linha</label><textarea id="f-topics" name="topics" required maxlength="20000" placeholder="Interpretação de textos\nOrtografia oficial"></textarea><p class="help">Você pode usar títulos como “1.2 Concordância nominal” para manter a referência do edital.</p>',async f=>{for(const name of f.get('topics').split('\n').map(s=>s.trim()).filter(Boolean))await save('topic',null,{exam:active,subject:f.get('subject'),name,status:'pending'})})},
 async toggle(id){const t=topic(id);if(t.status==='done')await save('topic',id,{status:'pending'});else await complete(t);await refresh();void synchronize()},
 detail(id){const t=topic(id);form('Detalhes do assunto',field('name','Título','text',t.name,'required maxlength="300"')+field('url','Link de material (opcional)','url',t.url||'')+`<label for="f-notes">Anotações</label><textarea id="f-notes" name="notes" maxlength="20000">${esc(t.notes||'')}</textarea>`,async f=>{const url=f.get('url');if(url&&!/^https?:\/\//i.test(url))throw Error('Use um endereço HTTP ou HTTPS.');await save('topic',id,{name:f.get('name').trim(),url,notes:f.get('notes')})})},
 start(id){if(getTimer())throw Error('Finalize ou descarte a sessão atual na tela Hoje.');const t=topic(id);if(!t)throw Error('Assunto não encontrado.');storeTimer({topic:id,exam:active,name:t.name,started:Date.now(),elapsed:0,running:true});location.hash='hoje';render()},
 pause(){const t=getTimer();if(!t)return;storeTimer({...t,elapsed:elapsed(t),started:Date.now(),running:!t.running});render()},
 finish(){const t=getTimer();if(!t)return;storeTimer({...t,elapsed:elapsed(t),running:false});active=t.exam;sessionForm(t.topic,'',getTimer());lockTopic(t.topic);render()},
 discard(){if(confirm('Descartar o cronômetro sem registrar esta sessão?')){storeTimer(null);render()}},
 session(id){sessionForm(id)},review(id){const r=items('review').find(x=>x.id===id);sessionForm(r.topic,id);lockTopic(r.topic)},
 reschedule(id){const r=items('review').find(x=>x.id===id);form('Reagendar revisão',field('date','Nova data','date',r.date,'required'),async f=>save('review',id,{date:f.get('date')}))},
 day(id){day=Number(id);render()},
 plan(){if(!needExam())return;if(!items('topic').length)throw Error('Cadastre assuntos primeiro.');form('Bloco semanal',select('topic','Assunto',options(items('topic')))+select('day','Dia da semana',['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((x,i)=>`<option value="${i}">${x}</option>`).join(''))+field('time','Horário de início','time','19:00','required')+field('minutes','Duração em minutos','number',50,'min="1" max="1440" required'),async f=>{const day=Number(f.get('day')),time=f.get('time'),minutes=Number(f.get('minutes'));const number=s=>Number(s.slice(0,2))*60+Number(s.slice(3));if(number(time)+minutes>1440)throw Error('Divida blocos que atravessam a meia-noite em dois dias.');if(items('plan').some(p=>p.day===day&&number(time)<number(p.time)+p.minutes&&number(time)+minutes>number(p.time)))throw Error('Esse horário se sobrepõe a outro bloco.');await save('plan',null,{exam:active,topic:f.get('topic'),day,time,minutes})})},
 async delete(id){const x=state.find(x=>x.id===id);if(confirm('Excluir este registro? A exclusão será sincronizada com seus aparelhos.')){await save(x.kind,id,{deleted:true});await refresh();void synchronize()}},
 mock(){if(!needExam())return;const subs=items('subject');if(!subs.length)throw Error('Cadastre disciplinas e seus pesos primeiro.');form('Registrar simulado',field('name','Identificação','text','','required maxlength="160"')+field('date','Data','date',today(),'required')+subs.map(s=>`<h3 style="margin-top:20px">${esc(s.name)} · peso ${s.weight}</h3><div class="fields"><div>${field('q-'+s.id,'Total de questões','number',0,'min="0" max="10000" required')}</div><div>${field('r-'+s.id,'Acertos','number',0,'min="0" max="10000" required')}</div></div>`).join('')+'<p class="help">Cálculo por acertos × peso. Penalidades por erro e notas mínimas por bloco não estão configuradas.</p>',async f=>{const parts=subs.map(s=>({name:s.name,total:Number(f.get('q-'+s.id)),right:Number(f.get('r-'+s.id)),weight:s.weight}));if(parts.some(p=>p.right>p.total))throw Error('Confira os acertos por disciplina.');const max=parts.reduce((a,p)=>a+p.total*p.weight,0);if(!max)throw Error('Informe ao menos uma questão.');await save('mock',null,{exam:active,name:f.get('name'),date:f.get('date'),parts,max,score:parts.reduce((a,p)=>a+p.right*p.weight,0)})})},
 theme(){document.body.classList.toggle('dark');localStorage.setItem('estudo-theme',document.body.classList.contains('dark')?'dark':'light')},
 login(){if(!configured)throw Error('Configure config.js com os dados públicos do Supabase.');form('Conectar sua conta',field('email','E-mail','email','','required autocomplete="email"')+field('password','Senha','password','','required minlength="8" autocomplete="current-password"')+'<label class="check"><input type="checkbox" name="signup">Criar uma nova conta</label>',async f=>{const ok=await login(f.get('email'),f.get('password'),f.has('signup'));if(!ok){notice('Conta criada. Confirme o e-mail e depois entre com sua senha.');return}const local=(await allEvents()).some(e=>e.owner==='local');if(local&&confirm('Enviar os registros locais deste aparelho para esta conta?'))await adoptLocal();active='';notice('Conta conectada. Sincronizando seus registros.');})},
 async logout(){await logout();active='';await refresh();notice('Você saiu. Os dados da conta ficam separados dos registros locais.')},
 async sync(){await synchronize();if(owner()==='local')notice('Entre em uma conta para sincronizar.')},
 backup(){const blob=new Blob([JSON.stringify({format:'estudo-v1',events},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='estudo-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},
 restore(){modal('Restaurar backup','<p class="help">Selecione um backup do Estudo. Os registros serão combinados com os dados da conta atual.</p><input id="backup-file" type="file" accept="application/json"><p id="restore-status" role="status"></p>');$('#backup-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('Limite de 10 MB por backup.');const data=JSON.parse(await file.text());if(data.format!=='estudo-v1'||!Array.isArray(data.events))throw Error('Formato de backup incompatível.');const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;for(const x of data.events)if(!uuid.test(x.id)||!uuid.test(x.entity)||!['exam','subject','topic','session','review','plan','mock'].includes(x.kind)||!x.payload||Array.isArray(x.payload)||typeof x.payload!=='object'||!Number.isFinite(Date.parse(x.at)))throw Error('Backup contém registros inválidos.');if(!confirm('Combinar '+data.events.length+' eventos com o histórico atual?'))return;const {putEvents}=await import('./data.js');const existing=new Set((await allEvents()).map(x=>x.id));await putEvents(data.events.filter(x=>!existing.has(x.id)).map(x=>({...x,owner:owner(),synced:false})));$('#dialog').close();await refresh();void synchronize();notice('Backup restaurado.')}catch(err){$('#restore-status').textContent=err.message}}}
};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{await actions[b.dataset.action]?.(b.dataset.id)}catch(err){notice(err.message)}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;filter=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.id==='filter'){filterState=e.target.value;render()}if(e.target.id==='exam-select'){active=e.target.value;localStorage.setItem('estudo-active',active);render()}});
$('#theme').onclick=actions.theme;$('#sync').onclick=actions.sync;window.addEventListener('hashchange',render);window.addEventListener('online',()=>void synchronize());window.addEventListener('offline',render);window.addEventListener('focus',()=>void refresh().then(synchronize));
setInterval(()=>{const t=getTimer();if(t&&$('#clock'))$('#clock').textContent=clock(elapsed(t))},1000);setInterval(()=>{if(navigator.onLine&&!$('#dialog').open)void synchronize()},30000);
if(localStorage.getItem('estudo-theme')==='dark')document.body.classList.add('dark');
try{await openDB();await refresh();void synchronize()}catch(e){notice('Não foi possível abrir o armazenamento local. Verifique permissões do navegador. '+e.message)}
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>notice('Não foi possível ativar o modo offline.'));
