import {leaves,leavesOf,progress,topicPath,distribution} from './study.js';
const pct=(a,b)=>b?Math.round(a/b*100):0;
const duration=n=>`${Math.floor(n/60)}h${n%60?String(n%60).padStart(2,'0'):''}`;
const date=d=>d?d.split('-').reverse().join('/'):'A definir';
function meter(p,label='Cobertura'){return `<div class="progress-track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${p}"><span style="width:${p}%"></span></div>`}
function stat(title,value,caption){return `<div class="metric"><span>${title}</span><strong>${value}</strong><small>${caption}</small></div>`}
function empty(title,body,button=''){return `<div class="empty-state"><h3>${title}</h3><p>${body}</p>${button}</div>`}
function sectionTitle(title,aside=''){return `<div class="section-head"><h2>${title}</h2>${aside}</div>`}
function status(c,t){if(t.status==='done')return 'Estudado';if(c.items('session').some(s=>s.topic===t.id))return 'Em andamento';return 'Não iniciado'}
function topicFacts(c,t){const logs=c.items('session').filter(s=>s.topic===t.id),q=logs.reduce((a,s)=>a+s.questions,0),r=logs.reduce((a,s)=>a+s.right,0),rev=c.items('review').filter(x=>x.topic===t.id&&!x.done).sort((a,b)=>a.date.localeCompare(b.date))[0];return {q,r,rev}}
export function home(c){
 const ts=c.items('topic'),ss=c.items('session'),p=progress(ts),today=c.today(),due=c.reviews();
 const start=new Date(today+'T12:00:00');start.setDate(start.getDate()-(start.getDay()+6)%7);
 const week=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}-${String(start.getDate()).padStart(2,'0')}`;
 const minutes=ss.filter(s=>s.date>=week&&s.date<=today).reduce((a,s)=>a+s.minutes,0),q=ss.reduce((a,s)=>a+s.questions,0),r=ss.reduce((a,s)=>a+s.right,0);
 const plan=c.items('plan').filter(s=>s.day===new Date().getDay()).sort((a,b)=>a.time.localeCompare(b.time));
 const studied=new Set(ss.filter(s=>s.date===today).map(s=>s.topic));
 const nextPlan=plan.find(x=>!studied.has(x.topic));
 const next= c.topic(due[0]?.topic)||c.topic(nextPlan?.topic)||leaves(ts).find(t=>t.status!=='done');
 const goal=c.exam()?.weeklyMinutes||600;
 const days=Array.from({length:7},(_,i)=>{const d=c.future(week,i);return {date:d,mins:ss.filter(s=>s.date===d).reduce((a,s)=>a+s.minutes,0)}});
 return `<div class="page-intro"><p>O essencial para a sua próxima sessão.</p><span class="date-label">${new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span></div>
 <section class="focus-card"><div class="focus-copy"><span class="eyebrow">${due.length?'REVISÃO PRIORITÁRIA':'PRÓXIMO PASSO'}</span><h2>${next?c.esc(next.name):ts.length?'Primeira passagem concluída.':'Aguardando conteúdo do edital.'}</h2><p>${next?c.esc(c.subject(next.subject)?.name||'')+' · '+(due.length?'Comece por uma revisão pendente.':'Continue pelo seu planejamento.'):ts.length?'Mantenha as revisões e acompanhe o aproveitamento.':'O edital de Suporte Técnico Administrativo será estruturado aqui.'}</p><div class="actions">${next?(due.length?c.button('Revisar agora','review',due[0].id,'primary'):c.button('Iniciar sessão','start',next.id,'primary')):''}<a class="text-link" href="#edital">Ver meu edital <span aria-hidden="true">→</span></a></div></div><div class="coverage"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="49"/><circle class="ring-value" cx="60" cy="60" r="49" stroke-dasharray="${p.percent*3.0788} 307.88"/></svg><div><strong>${p.percent}<small>%</small></strong><span>do edital estudado</span></div><p>${p.done} de ${p.total} itens</p></div></section>
 ${c.timerHTML()}<div class="metrics">${stat('TEMPO NA SEMANA',duration(minutes),`Meta de ${duration(goal)}`)}${stat('QUESTÕES',q,q?`${pct(r,q)}% de aproveitamento`:'A amostra começa com sua primeira sessão')}${stat('REVISÕES PENDENTES',due.length,due.filter(x=>x.date<today).length+' atrasadas')}${stat('CONSTÂNCIA',days.filter(d=>d.mins>0).length+' / 7','Dias com estudo nesta semana')}</div>
 <div class="home-grid"><section class="panel"><div class="section-head"><h2>Plano de hoje</h2><a href="#plano">Planejamento</a></div>${plan.length?plan.map(x=>`<div class="plan-row"><div class="time-block">${c.esc(x.time)}<small>${x.minutes} min</small></div><div><h3>${c.esc(c.topic(x.topic)?.name||'Assunto')}</h3><p>${c.esc(c.subject(c.topic(x.topic)?.subject)?.name||'')} ${studied.has(x.topic)?'· Sessão registrada hoje':''}</p></div>${c.button(studied.has(x.topic)?'Repetir':'Iniciar','start',x.topic,'compact')}</div>`).join(''):empty('Rotina de estudo.','Os blocos de estudo diários aparecerão aqui.')}</section>
 <section class="panel"><div class="section-head"><h2>Ritmo da semana</h2><span class="quiet-label">Minutos por dia</span></div><div class="week-chart">${days.map((d,i)=>`<div class="day-column ${d.date===today?'current':''}"><span>${d.mins||'—'}</span><div class="bar-space"><i style="height:${d.mins?Math.max(5,d.mins/Math.max(...days.map(x=>x.mins),1)*100):0}%"></i></div><small>${['S','T','Q','Q','S','S','D'][i]}</small></div>`).join('')}</div><p class="chart-caption">${duration(minutes)} de ${duration(goal)} planejadas</p>${meter(Math.min(100,pct(minutes,goal)),'Meta semanal')}</section></div>
 <section class="panel"><div class="section-head"><h2>Mapa das disciplinas</h2><a href="#edital">Abrir conteúdo</a></div>${subjectSummary(c)}</section>`;
}
function subjectSummary(c){return c.items('subject').map(s=>{const p=progress(c.items('topic').filter(t=>t.subject===s.id)),pending=c.reviews().filter(r=>c.topic(r.topic)?.subject===s.id).length;return `<div class="subject-overview"><div><h3>${c.esc(s.name)}</h3><small>${p.done}/${p.total} itens estudados${pending?' · '+pending+' revisões pendentes':''}</small></div><div>${meter(p.percent,c.esc(s.name))}<strong>${p.percent}%</strong></div>${c.button('Abrir','open-subject',s.id,'compact')}</div>`}).join('')||empty('Edital direcionado.','As disciplinas do edital aparecerão aqui com cobertura e progresso.')}
export function syllabus(c){
 const ts=c.items('topic'),p=progress(ts),q=c.filter.toLocaleLowerCase();
 const matches=t=>{const s=status(c,t),f=topicFacts(c,t);return (!q||topicPath(ts,t.id).toLocaleLowerCase().includes(q)||c.subject(t.subject)?.name.toLocaleLowerCase().includes(q))&&(c.filterState==='all'||(c.filterState==='pending'&&s!=='Estudado')||(c.filterState==='done'&&s==='Estudado')||(c.filterState==='review'&&f.rev?.date<=c.today()))};
 function branch(t,depth=0,seen=new Set()){
  if(seen.has(t.id)||depth>20)return '';seen.add(t.id);
  const kids=ts.filter(x=>x.parent===t.id),leaf=leavesOf(ts,t.id),visible=leaf.some(matches);
  if(!visible)return '';
  if(kids.length){const p=progress(leaf),key='topic:'+t.id;return `<details class="topic-branch" data-open-key="${key}" ${c.isOpen(key)||q?'open':''}><summary><span class="chevron" aria-hidden="true"></span><span class="branch-title">${c.esc(t.name)}</span><span class="quiet-label">${p.done}/${p.total}</span><span class="mini-percent">${p.percent}%</span></summary><div class="branch-body">${kids.map(x=>branch(x,depth+1,new Set(seen))).join('')}</div></details>`}
  const s=status(c,t),f=topicFacts(c,t),key='leaf:'+t.id;
  return `<details class="topic-leaf ${t.status==='done'?'is-done':''}" data-open-key="${key}" ${c.isOpen(key)?'open':''}><summary><span class="state-dot ${t.status==='done'?'done':s==='Em andamento'?'started':''}" aria-hidden="true">${t.status==='done'?'✓':''}</span><span class="leaf-title">${c.esc(t.name)}<small>${f.rev?(f.rev.date<c.today()?'Revisão atrasada · ': 'Revisar em ')+date(f.rev.date):f.q?`${f.q} questões · ${pct(f.r,f.q)}% acertos`:'Sem revisão programada'}</small></span><span class="state-label">${s}</span><span class="chevron" aria-hidden="true"></span></summary><div class="topic-detail"><div class="topic-facts"><span>Questões <strong>${f.q}</strong></span><span>Aproveitamento <strong>${f.q?pct(f.r,f.q)+'%':'—'}</strong></span><span>Revisões feitas <strong>${c.items('review').filter(r=>r.topic===t.id&&r.done).length}</strong></span></div>${t.notes?`<p class="topic-notes">${c.esc(t.notes)}</p>`:''}${/^https?:\/\//i.test(t.url||'')?`<p><a href="${c.esc(t.url)}" target="_blank" rel="noopener noreferrer">Abrir material de estudo ↗</a></p>`:''}<div class="actions">${c.button('Estudar','start',t.id,'primary compact')}${c.button('Registrar','session',t.id,'compact')}${c.button(t.status==='done'?'Reabrir assunto':'Marcar estudado','toggle',t.id,'compact')}</div></div></details>`;
 }
 let count=0;
 const content=c.items('subject').map((s,i)=>{const own=ts.filter(t=>t.subject===s.id),sub=progress(own),body=own.filter(t=>!t.parent||!own.some(p=>p.id===t.parent)).map(t=>branch(t)).join('');if(!body&&(q||c.filterState!=='all'))return '';count++;const key='subject:'+s.id,due=c.reviews().filter(r=>c.topic(r.topic)?.subject===s.id).length;return `<details class="subject-card" data-open-key="${key}" ${c.isOpen(key)||q||c.filterState!=='all'?'open':''}><summary><span class="subject-number">${String(i+1).padStart(2,'0')}</span><div class="subject-title"><h2>${c.esc(s.name)}</h2><small>${sub.done} de ${sub.total} itens · ${due?due+' revisões pendentes':'Revisões em dia'}</small></div><div class="subject-meter"><span>${sub.percent}%</span>${meter(sub.percent,c.esc(s.name))}</div><span class="chevron" aria-hidden="true"></span></summary><div class="subject-body">${body||empty('Conteúdo do edital.','Os tópicos deste edital serão inseridos de forma automatizada.') }<div class="subject-footer"><span>Peso por questão: ${s.weight}</span></div></div></details>`}).join('');
 return `<div class="page-intro"><p>Abra uma disciplina. Avance um assunto por vez.</p><span>${p.done} / ${p.total} itens estudados</span></div><div class="syllabus-toolbar"><input id="search" aria-label="Buscar conteúdo" placeholder="Buscar disciplina, tópico ou subtópico" value="${c.esc(c.filter)}"><select id="filter" aria-label="Filtrar conteúdo">${[['all','Todo o edital'],['pending','Por estudar'],['done','Estudados'],['review','Revisões pendentes']].map(([v,n])=>`<option value="${v}" ${c.filterState===v?'selected':''}>${n}</option>`).join('')}</select></div><div class="syllabus-meta"><span>O progresso considera apenas os assuntos finais, sem contagem dupla.</span><div>${c.button('Expandir','expand','','text-button')}${c.button('Recolher','collapse','','text-button')}</div></div>${content||empty(count?'Nenhum resultado.':'Edital Bacen — Suporte Técnico Administrativo',q||c.filterState!=='all'?'Tente outro termo ou filtro.':'Envie o edital para organizarmos as disciplinas e os blocos de estudo.')}`;
}
export function planner(c){
 const goal=c.exam()?.weeklyMinutes||600,shares=distribution(c.items('subject'),c.items('topic'),c.items('session'),goal);
 const due=c.items('review').filter(r=>!r.done&&c.topic(r.topic)).sort((a,b)=>a.date.localeCompare(b.date));
 return `<div class="page-intro"><p>Distribua o tempo. Mantenha as revisões visíveis.</p></div><section class="panel"><div class="section-head"><h2>Distribuição da semana</h2><span>${duration(goal)} disponíveis</span></div><p class="help">Sugestão por peso da matéria, conteúdo restante e aproveitamento.</p><div class="distribution-grid">${shares.map(s=>`<div class="distribution-item"><h3>${c.esc(s.name)}</h3><strong>${duration(s.minutes)}</strong><small>${s.percent}% estudado · ${s.accuracy===null?'sem amostra de questões':s.accuracy+'% de acertos'}</small>${meter(pct(s.minutes,goal),'Fração da semana')}</div>`).join('')||empty('Edital Bacen.','A distribuição aparece quando os tópicos forem gerados.')}</div></section><section class="panel"><div class="section-head"><h2>Agenda semanal</h2><span>Blocos diários</span></div><div class="day-tabs">${[1,2,3,4,5,6,0].map(i=>`<button data-action="day" data-id="${i}" aria-pressed="${c.day===i}">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][i]}</button>`).join('')}</div>${c.planRows(c.items('plan').filter(p=>p.day===c.day).sort((a,b)=>a.time.localeCompare(b.time)))}</section><section class="panel"><div class="section-head"><h2>Revisões programadas</h2><span>${due.length} pendentes</span></div>${due.map(r=>`<div class="review-row"><span class="review-date ${r.date<c.today()?'overdue':''}">${date(r.date)}<small>${r.date<c.today()?'Atrasada':r.date===c.today()?'Hoje':'Programada'}</small></span><div><h3>${c.esc(c.topic(r.topic)?.name)}</h3><p>${c.esc(c.subject(c.topic(r.topic)?.subject)?.name||'')}</p></div><div class="actions">${c.button('Revisar','review',r.id,'compact')}${c.button('Reagendar','reschedule',r.id,'text-button')}</div></div>`).join('')||empty('Revisões em dia.','Ao estudar um assunto, as próximas revisões são preparadas automaticamente.')}</section>`;
}
